#!/bin/bash

prg=./shell

for t in Test/Test_* ; do
    echo -n "${t##*/}: "       
    $prg < "$t/inp" > "$t/out" 2>&1
    if diff -q -w "$t/exp" "$t/out" >/dev/null 2>&1; then
        echo "passed"
    else
        echo "failed"
    fi
done
